import dotenv from "dotenv";

dotenv.config();

const ENV = process.env;
const signalAssets = ["btc", "eth", "sol", "xrp"] as const;
const signalWindows = ["5m", "15m"] as const;
const qmonExecutionMode = ENV.QMON_EXECUTION_MODE === "real" ? "real" : "paper";
const qmonUseMinimumEntryShares = ENV.QMON_USE_MINIMUM_ENTRY_SHARES !== "false";
const QMON_REAL_EMERGENCY_MAX_SESSION_LOSS_USD = Number(ENV.QMON_REAL_EMERGENCY_MAX_SESSION_LOSS_USD || 10);
const qmonRealRequireWalkForward = ENV.QMON_REAL_REQUIRE_WALK_FORWARD !== "false";
const qmonPresetQmonsEnabled = ENV.QMON_PRESET_QMONS_ENABLED !== "false";
const polymarketSignatureType = ENV.POLYMARKET_SIGNATURE_TYPE !== undefined ? Number(ENV.POLYMARKET_SIGNATURE_TYPE) : undefined;
const polymarketMaxAllowedSlippage = ENV.POLYMARKET_MAX_ALLOWED_SLIPPAGE !== undefined ? Number(ENV.POLYMARKET_MAX_ALLOWED_SLIPPAGE) : undefined;
const polymarketSafeMaxBuyAmount = Number(ENV.POLYMARKET_SAFE_MAX_BUY_AMOUNT || 15);

const config = {
  RESPONSE_CONTENT_TYPE: ENV.RESPONSE_CONTENT_TYPE || "application/json",
  DEFAULT_PORT: Number(ENV.PORT || 3000),
  SERVICE_NAME: ENV.SERVICE_NAME || "@sha3/polymarket-quant",
  SNAPSHOT_INTERVAL_MS: Number(ENV.SNAPSHOT_INTERVAL_MS || 500),
  SIGNAL_HORIZONS_SEC: [30, 120, 300] as readonly number[],
  SIGNAL_ASSETS: signalAssets,
  SIGNAL_WINDOWS: signalWindows,
  SIGNAL_EXCHANGES: ["binance", "coinbase", "kraken", "okx"] as readonly string[],
  MAX_MAX_TRADES_PER_WINDOW: Number(ENV.MAX_MAX_TRADES_PER_WINDOW || 4), // Maximum value for maxTradesPerWindow gene
  MAX_MAX_SLIPPAGE_BPS: Number(ENV.MAX_MAX_SLIPPAGE_BPS || 1500), // Maximum value for maxSlippageBps gene
  QMON_PERSIST_CHECKPOINT_MS: Number(ENV.QMON_PERSIST_CHECKPOINT_MS || 10_000),
  QMON_EVOLUTION_ENABLED: ENV.QMON_EVOLUTION_ENABLED !== "false",
  QMON_EVOLUTION_REPLACEMENT_RATE: Number(ENV.QMON_EVOLUTION_REPLACEMENT_RATE || 0.02),
  QMON_EVOLUTION_MIN_PARENT_WINDOWS: Number(ENV.QMON_EVOLUTION_MIN_PARENT_WINDOWS || 10),
  QMON_EVOLUTION_NEWBORN_PROTECTION_WINDOWS: Number(ENV.QMON_EVOLUTION_NEWBORN_PROTECTION_WINDOWS || 5),
  QMON_EVOLUTION_MUTATION_RATE: Number(ENV.QMON_EVOLUTION_MUTATION_RATE || 0.08),
  QMON_GENETIC_POPULATION_SIZE: Number(ENV.QMON_GENETIC_POPULATION_SIZE || 200),
  QMON_PRESET_QMON_COUNT: Number(ENV.QMON_PRESET_QMON_COUNT || 400),
  QMON_PRESET_QMONS_ENABLED: qmonPresetQmonsEnabled,
  QMON_HYDRATION_WINDOW_COUNT: Number(ENV.QMON_HYDRATION_WINDOW_COUNT || 10),
  QMON_HYDRATION_SNAPSHOT_STRIDE: Number(ENV.QMON_HYDRATION_SNAPSHOT_STRIDE || 10),
  QMON_MIN_ENTRY_EDGE_BPS: Number(ENV.QMON_MIN_ENTRY_EDGE_BPS || 35),
  QMON_MIN_ENTRY_NET_EV_USD: Number(ENV.QMON_MIN_ENTRY_NET_EV_USD || 0.08),
  QMON_MIN_ENTRY_CONFIRMATIONS: Number(ENV.QMON_MIN_ENTRY_CONFIRMATIONS || 2),
  QMON_MIN_ENTRY_FILL_QUALITY: Number(ENV.QMON_MIN_ENTRY_FILL_QUALITY || 0.5),
  QMON_MAX_ENTRY_SLIPPAGE_BPS: Number(ENV.QMON_MAX_ENTRY_SLIPPAGE_BPS || 80),
  QMON_EXECUTION_MODE: qmonExecutionMode,
  QMON_USE_MINIMUM_ENTRY_SHARES: qmonUseMinimumEntryShares,
  QMON_REAL_EMERGENCY_MAX_SESSION_LOSS_USD,
  QMON_REAL_REQUIRE_WALK_FORWARD: qmonRealRequireWalkForward,
  QMON_REAL_MIN_WF_TRADES: Number(ENV.QMON_REAL_MIN_WF_TRADES || 10),
  QMON_REAL_MAX_WF_DRAWDOWN_USD: Number(ENV.QMON_REAL_MAX_WF_DRAWDOWN_USD || 4),
  QMON_REAL_MIN_WF_NET_PNL_USD: Number(ENV.QMON_REAL_MIN_WF_NET_PNL_USD || 1),
  QMON_REAL_MAX_WF_FEE_RATIO: Number(ENV.QMON_REAL_MAX_WF_FEE_RATIO || 0.45),
  QMON_REAL_MAX_WF_SLIPPAGE_BPS: Number(ENV.QMON_REAL_MAX_WF_SLIPPAGE_BPS || 80),
  POLYMARKET_PRIVATE_KEY: ENV.POLYMARKET_PRIVATE_KEY,
  POLYMARKET_FUNDER_ADDRESS: ENV.POLYMARKET_FUNDER_ADDRESS,
  POLYMARKET_SIGNATURE_TYPE: polymarketSignatureType,
  POLYMARKET_MAX_ALLOWED_SLIPPAGE: polymarketMaxAllowedSlippage,
  POLYMARKET_SAFE_MAX_BUY_AMOUNT: polymarketSafeMaxBuyAmount,
  QMON_REAL_CONFIRMATION_TIMEOUT_MS: Number(ENV.QMON_REAL_CONFIRMATION_TIMEOUT_MS || 15_000),
} as const;

export default config;
