import dotenv from "dotenv";

dotenv.config();

const ENV = process.env;
const signalAssets = ["btc", "eth", "sol", "xrp"] as const;
const signalWindows = ["5m", "15m"] as const;
const qmonExecutionMode = ENV.QMON_EXECUTION_MODE === "real" ? "real" : "paper";
const qmonUseMinimumEntryShares = ENV.QMON_USE_MINIMUM_ENTRY_SHARES !== "false";
const QMON_REAL_EMERGENCY_MAX_SESSION_LOSS_USD = Number(ENV.QMON_REAL_EMERGENCY_MAX_SESSION_LOSS_USD || 10);
const polymarketSignatureType = ENV.POLYMARKET_SIGNATURE_TYPE !== undefined ? Number(ENV.POLYMARKET_SIGNATURE_TYPE) : undefined;
const polymarketMaxAllowedSlippage = ENV.POLYMARKET_MAX_ALLOWED_SLIPPAGE !== undefined ? Number(ENV.POLYMARKET_MAX_ALLOWED_SLIPPAGE) : undefined;
const polymarketSafeMaxBuyAmount = Number(ENV.POLYMARKET_SAFE_MAX_BUY_AMOUNT || 15);

const config = {
  RESPONSE_CONTENT_TYPE: ENV.RESPONSE_CONTENT_TYPE || "application/json",
  DEFAULT_PORT: Number(ENV.PORT || 3000),
  SERVICE_NAME: ENV.SERVICE_NAME || "@sha3/polymarket-quant",
  SNAPSHOT_INTERVAL_MS: Number(ENV.SNAPSHOT_INTERVAL_MS || 500),
  SIGNAL_HORIZONS_SEC: [30, 120, 300] as readonly number[],
  SIGNAL_ASSETS: signalAssets,
  SIGNAL_WINDOWS: signalWindows,
  SIGNAL_EXCHANGES: ["binance", "coinbase", "kraken", "okx"] as readonly string[],
  MAX_MAX_TRADES_PER_WINDOW: Number(ENV.MAX_MAX_TRADES_PER_WINDOW || 4), // Maximum value for maxTradesPerWindow gene
  MAX_MAX_SLIPPAGE_BPS: Number(ENV.MAX_MAX_SLIPPAGE_BPS || 1500), // Maximum value for maxSlippageBps gene
  QMON_PERSIST_CHECKPOINT_MS: Number(ENV.QMON_PERSIST_CHECKPOINT_MS || 10_000),
  QMON_EVOLUTION_ENABLED: ENV.QMON_EVOLUTION_ENABLED !== "false",
  QMON_EVOLUTION_REPLACEMENT_RATE: Number(ENV.QMON_EVOLUTION_REPLACEMENT_RATE || 0.02),
  QMON_EVOLUTION_MIN_PARENT_WINDOWS: Number(ENV.QMON_EVOLUTION_MIN_PARENT_WINDOWS || 10),
  QMON_EVOLUTION_NEWBORN_PROTECTION_WINDOWS: Number(ENV.QMON_EVOLUTION_NEWBORN_PROTECTION_WINDOWS || 5),
  QMON_EVOLUTION_MUTATION_RATE: Number(ENV.QMON_EVOLUTION_MUTATION_RATE || 0.08),
  QMON_HYDRATION_WINDOW_COUNT: Number(ENV.QMON_HYDRATION_WINDOW_COUNT || 10),
  QMON_HYDRATION_SNAPSHOT_STRIDE: Number(ENV.QMON_HYDRATION_SNAPSHOT_STRIDE || 10),
  QMON_EXECUTION_MODE: qmonExecutionMode,
  QMON_USE_MINIMUM_ENTRY_SHARES: qmonUseMinimumEntryShares,
  QMON_REAL_EMERGENCY_MAX_SESSION_LOSS_USD,
  POLYMARKET_PRIVATE_KEY: ENV.POLYMARKET_PRIVATE_KEY,
  POLYMARKET_FUNDER_ADDRESS: ENV.POLYMARKET_FUNDER_ADDRESS,
  POLYMARKET_SIGNATURE_TYPE: polymarketSignatureType,
  POLYMARKET_MAX_ALLOWED_SLIPPAGE: polymarketMaxAllowedSlippage,
  POLYMARKET_SAFE_MAX_BUY_AMOUNT: polymarketSafeMaxBuyAmount,
  QMON_REAL_CONFIRMATION_TIMEOUT_MS: Number(ENV.QMON_REAL_CONFIRMATION_TIMEOUT_MS || 15_000),
} as const;

export default config;
